// Generated by integrations/google-apps-script/build-intakes.mjs. Do not edit by hand.
// Standalone project ONLY: never install in or configure with the Primary production backend.
const FORM_VERSION = "secondary-learner-profile-v1";
const LEARNER_CONSENT_ROUTES = [
    "The learner understands how this information will be used and has authorised me to communicate this consent on their behalf.",
    "The learner is not currently able to understand and give informed consent to this use of their information, so I am giving consent as a person with parental responsibility or documented legal authority.",
];
const RELATIONSHIPS = [
    "Parent",
    "Guardian or carer",
    "Medical or health professional",
    "Friend",
    "Employer",
    "Other family member",
    "Education or support professional",
    "Other",
];
const CONTACT_METHODS = ["Email", "Telephone", "Text message", "WhatsApp"];
const CONTACT_TIMES = [
    "Weekday morning",
    "Weekday afternoon",
    "Weekday evening",
    "Weekend morning",
    "Weekend afternoon",
    "Weekend evening",
];
const YEAR_GROUPS = ["Year 7", "Year 8", "Year 9", "Year 10", "Year 11", "Other / not currently following a standard school year"];
const SUBJECTS = ["English", "Maths", "Science", "Other"];
const NEEDS_STATUSES = [
    "Yes: diagnosed",
    "Yes: suspected or informally identified",
    "An assessment is currently underway",
    "No known additional needs",
    "Prefer not to say",
];
const RELEVANT_AREAS = [
    "ADHD",
    "Autism / autistic",
    "Auditory processing",
    "Dyscalculia",
    "Dysgraphia",
    "Dyslexia",
    "Dyspraxia or developmental coordination difficulties",
    "Speech, language or communication needs",
    "Visual processing",
    "Sensory processing",
    "Emotional or mental-health needs",
    "Physical or medical needs",
    "Another need not listed",
    "Prefer not to say",
];
const EHCP_STATUSES = [
    "Yes",
    "No",
    "An EHC needs assessment or plan is currently in progress",
    "Not sure",
];
const SESSION_LENGTHS = [
    "30 minutes",
    "45 minutes",
    "60 minutes",
    "90 minutes",
    "Not sure",
];
const SESSION_FREQUENCIES = [
    "3 per week",
    "2 per week",
    "1 per week",
    "1 per fortnight",
    "Pay as you go",
    "Not sure yet",
];
const WIDER_SUPPORT_OPTIONS = ["Yes, I'd like to discuss this", "No, tutoring only for now", "Maybe later", "Not sure"];
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;
const PHONE_CONTACT_METHODS = new Set(["Telephone", "Text message", "WhatsApp"]);
const SPECIAL_CATEGORY_RELATIONSHIPS = new Set(["Parent", "Guardian or carer"]);
const NEEDS_AREAS_VISIBLE = new Set([
    "Yes: diagnosed",
    "Yes: suspected or informally identified",
    "An assessment is currently underway",
]);
function isRecord(value) {
    return typeof value === "object" && value !== null && !Array.isArray(value);
}
function textValue(value, maximum) {
    if (typeof value !== "string")
        return null;
    const trimmed = value.trim();
    return trimmed.length <= maximum ? trimmed : null;
}
function requiredText(source, key, path, maximum, errors) {
    const value = textValue(source[key], maximum);
    if (value === null || value.length === 0) {
        errors[path] = "Enter this information.";
        return "";
    }
    return value;
}
function optionalText(source, key, path, maximum, errors) {
    const value = textValue(source[key], maximum);
    if (value === null) {
        errors[path] = `Use ${maximum.toLocaleString("en-GB")} characters or fewer.`;
        return "";
    }
    return value;
}
function choice(source, key, path, allowed, errors) {
    const value = source[key];
    if (typeof value !== "string" || !allowed.includes(value)) {
        errors[path] = "Choose an option.";
        const fallback = allowed[0];
        if (fallback === undefined)
            throw new Error("Choice validation requires at least one allowed value");
        return fallback;
    }
    return value;
}
function optionalChoice(source, key, path, allowed, errors) {
    const value = source[key];
    if (value === "")
        return "";
    if (typeof value !== "string" || !allowed.includes(value)) {
        errors[path] = "Choose an available option or leave this blank.";
        return "";
    }
    return value;
}
function choices(source, key, path, allowed, errors, required) {
    const value = source[key];
    if (!Array.isArray(value) || value.some((item) => typeof item !== "string" || !allowed.includes(item))) {
        errors[path] = "Choose only from the available options.";
        return [];
    }
    const unique = [...new Set(value)];
    if (unique.length !== value.length)
        errors[path] = "Choose each option only once.";
    if (required && unique.length === 0)
        errors[path] = "Choose at least one option.";
    return unique;
}
function validDate(value) {
    if (!DATE_PATTERN.test(value))
        return false;
    const date = new Date(`${value}T00:00:00Z`);
    return !Number.isNaN(date.getTime()) && date.toISOString().startsWith(value) && date <= new Date();
}
function validateSecondaryRequest(input) {
    const errors = {};
    if (!isRecord(input))
        return { ok: false, errors: { form: "The form data is invalid." } };
    const respondent = isRecord(input.respondent) ? input.respondent : {};
    const learner = isRecord(input.learner) ? input.learner : {};
    const support = isRecord(input.supportProfile) ? input.supportProfile : {};
    const sessions = isRecord(input.sessionPreferences) ? input.sessionPreferences : {};
    const confirmations = isRecord(input.confirmations) ? input.confirmations : {};
    const formVersion = input.formVersion;
    if (formVersion !== FORM_VERSION)
        errors.formVersion = "Refresh the page before submitting.";
    const submissionId = textValue(input.submissionId, 64) ?? "";
    if (!UUID_PATTERN.test(submissionId))
        errors.submissionId = "Refresh the page before submitting.";
    const turnstileToken = textValue(input.turnstileToken, 2048) ?? "";
    if (!turnstileToken)
        errors.turnstileToken = "Complete the security check.";
    const honeypot = textValue(input.honeypot, 200) ?? "";
    const email = requiredText(respondent, "email", "respondent.email", 254, errors);
    if (email && !EMAIL_PATTERN.test(email))
        errors["respondent.email"] = "Enter a valid email address.";
    const respondentFirstName = requiredText(respondent, "firstName", "respondent.firstName", 100, errors);
    const respondentSurname = requiredText(respondent, "surname", "respondent.surname", 100, errors);
    const relationship = choice(respondent, "relationship", "respondent.relationship", RELATIONSHIPS, errors);
    const relationshipOther = optionalText(respondent, "relationshipOther", "respondent.relationshipOther", 160, errors);
    if (relationship === "Other" && !relationshipOther) {
        errors["respondent.relationshipOther"] = "Describe your relationship to the learner.";
    }
    if (relationship !== "Other" && relationshipOther)
        errors["respondent.relationshipOther"] = "Remove relationship details when Other is not selected.";
    const submittedPreferredContactMethods = choices(respondent, "preferredContactMethods", "respondent.preferredContactMethods", CONTACT_METHODS, errors, true);
    const preferredContactMethods = CONTACT_METHODS.filter((method) => submittedPreferredContactMethods.includes(method));
    if (respondent.preferredContactMethods === undefined ||
        (Array.isArray(respondent.preferredContactMethods) && respondent.preferredContactMethods.length === 0)) {
        errors["respondent.preferredContactMethods"] = "Choose at least one contact method.";
    }
    const mobile = optionalText(respondent, "mobile", "respondent.mobile", 40, errors);
    const selectedPhoneMethods = preferredContactMethods.filter((method) => PHONE_CONTACT_METHODS.has(method));
    if (selectedPhoneMethods.length > 0 && !mobile) {
        errors["respondent.mobile"] = `Enter a mobile number because you selected ${selectedPhoneMethods.join(", ")}.`;
    }
    const suitableContactTimes = choices(respondent, "suitableContactTimes", "respondent.suitableContactTimes", CONTACT_TIMES, errors, false);
    const learnerFirstName = requiredText(learner, "firstName", "learner.firstName", 100, errors);
    const learnerSurname = requiredText(learner, "surname", "learner.surname", 100, errors);
    const dateOfBirth = requiredText(learner, "dateOfBirth", "learner.dateOfBirth", 10, errors);
    if (dateOfBirth && !validDate(dateOfBirth))
        errors["learner.dateOfBirth"] = "Enter a valid date of birth.";
    const yearGroup = choice(learner, "yearGroup", "learner.yearGroup", YEAR_GROUPS, errors);
    const yearGroupOther = optionalText(learner, "yearGroupOther", "learner.yearGroupOther", 160, errors);
    if (yearGroup === "Other / not currently following a standard school year" && !yearGroupOther)
        errors["learner.yearGroupOther"] = "Describe the current year group or equivalent.";
    if (yearGroup !== "Other / not currently following a standard school year" && yearGroupOther)
        errors["learner.yearGroupOther"] = "Remove year-group details when Other is not selected.";
    const subjects = choices(learner, "subjects", "learner.subjects", SUBJECTS, errors, true);
    const subjectOther = optionalText(learner, "subjectOther", "learner.subjectOther", 160, errors);
    if (subjects.includes("Other") && !subjectOther)
        errors["learner.subjectOther"] = "Describe the other subject requiring support.";
    if (!subjects.includes("Other") && subjectOther)
        errors["learner.subjectOther"] = "Remove other-subject details when Other is not selected.";
    const submittedBoards = isRecord(learner.examBoards) ? learner.examBoards : {};
    const examBoards = { English: "", Maths: "", Science: "", Other: "" };
    for (const subject of SUBJECTS) {
        examBoards[subject] = optionalText(submittedBoards, subject, "learner.examBoards." + subject, 160, errors);
        if (!subjects.includes(subject) && examBoards[subject])
            errors["learner.examBoards." + subject] = "Remove the exam board for a subject that is not selected.";
    }
    const specialCategoryProvided = support.specialCategoryProvided;
    if (typeof specialCategoryProvided !== "boolean") {
        errors["supportProfile.specialCategoryProvided"] = "Choose whether you want to provide optional health, disability, SEND or neurodiversity information.";
    }
    const providesSpecialCategoryInformation = specialCategoryProvided === true;
    if (providesSpecialCategoryInformation && !SPECIAL_CATEGORY_RELATIONSHIPS.has(relationship)) {
        errors["supportProfile.specialCategoryProvided"] = "This form cannot accept health, disability, SEND, neurodiversity, diagnosis or EHCP information from this relationship. Ask Luke to arrange an appropriate information-sharing route.";
    }
    const needsStatus = optionalChoice(support, "needsStatus", "supportProfile.needsStatus", NEEDS_STATUSES, errors);
    const relevantAreas = choices(support, "relevantAreas", "supportProfile.relevantAreas", RELEVANT_AREAS, errors, false);
    if ((!needsStatus || !NEEDS_AREAS_VISIBLE.has(needsStatus)) && relevantAreas.length > 0) {
        errors["supportProfile.relevantAreas"] = "Remove areas that are not relevant to the selected answer.";
    }
    const supportNeeds = optionalText(support, "supportNeeds", "supportProfile.supportNeeds", 5000, errors);
    const helpfulStrategies = optionalText(support, "helpfulStrategies", "supportProfile.helpfulStrategies", 5000, errors);
    const unhelpfulApproaches = optionalText(support, "unhelpfulApproaches", "supportProfile.unhelpfulApproaches", 5000, errors);
    const otherBackground = optionalText(support, "otherBackground", "supportProfile.otherBackground", 5000, errors);
    const ehcpStatus = optionalChoice(support, "ehcpStatus", "supportProfile.ehcpStatus", EHCP_STATUSES, errors);
    const hasSpecialCategoryDetail = Boolean(needsStatus ||
        relevantAreas.length > 0 ||
        supportNeeds ||
        helpfulStrategies ||
        unhelpfulApproaches ||
        otherBackground ||
        ehcpStatus);
    if (!SPECIAL_CATEGORY_RELATIONSHIPS.has(relationship) && hasSpecialCategoryDetail) {
        errors["supportProfile.specialCategoryProvided"] = "This relationship cannot submit health, disability, SEND, neurodiversity, diagnosis, EHCP or related support information through this form. Ask Luke to arrange an appropriate information-sharing route.";
    }
    else if (!providesSpecialCategoryInformation && hasSpecialCategoryDetail) {
        errors["supportProfile.specialCategoryProvided"] = "Choose Yes and complete the Part 3 consent controls before providing optional health, disability, SEND, neurodiversity, diagnosis, EHCP or related support information.";
    }
    const sessionLength = choices(sessions, "sessionLength", "sessionPreferences.sessionLength", SESSION_LENGTHS, errors, true);
    const sessionFrequency = choices(sessions, "sessionFrequency", "sessionPreferences.sessionFrequency", SESSION_FREQUENCIES, errors, true);
    const widerSupport = optionalChoice(sessions, "widerSupport", "sessionPreferences.widerSupport", WIDER_SUPPORT_OPTIONS, errors);
    const learnerConsentRoute = optionalChoice(confirmations, "learnerConsentRoute", "confirmations.learnerConsentRoute", LEARNER_CONSENT_ROUTES, errors);
    if (confirmations.authorised !== true)
        errors["confirmations.authorised"] = "Confirm your authority and Privacy Policy acknowledgement.";
    if (confirmations.privacyAcknowledged !== true)
        errors["confirmations.privacyAcknowledged"] = "Confirm your authority and Privacy Policy acknowledgement.";
    if (providesSpecialCategoryInformation) {
        if (confirmations.specialCategoryConsent !== true) {
            errors["confirmations.specialCategoryConsent"] = "Give explicit consent or remove the optional health, disability, SEND and neurodiversity information.";
        }
        if (confirmations.specialCategoryAuthority !== true) {
            errors["confirmations.specialCategoryAuthority"] = "Complete the learner consent route in Part 3 or remove the optional information.";
        }
        if (!learnerConsentRoute) {
            errors["confirmations.learnerConsentRoute"] = "Choose the statement that applies to the learner’s consent.";
        }
    }
    else {
        if (confirmations.specialCategoryConsent === true) {
            errors["confirmations.specialCategoryConsent"] = "Remove consent when no optional special-category information is being provided.";
        }
        if (confirmations.specialCategoryAuthority === true) {
            errors["confirmations.specialCategoryAuthority"] = "Remove the authority confirmation when no optional special-category information is being provided.";
        }
        if (learnerConsentRoute) {
            errors["confirmations.learnerConsentRoute"] = "Remove the learner consent statement when no optional special-category information is being provided.";
        }
    }
    if (Object.keys(errors).length > 0)
        return { ok: false, errors };
    return {
        ok: true,
        request: {
            turnstileToken,
            honeypot,
            submission: {
                formVersion: FORM_VERSION,
                submissionId,
                respondent: {
                    email,
                    firstName: respondentFirstName,
                    surname: respondentSurname,
                    relationship,
                    relationshipOther,
                    mobile,
                    preferredContactMethods,
                    suitableContactTimes,
                },
                learner: {
                    firstName: learnerFirstName,
                    surname: learnerSurname,
                    dateOfBirth,
                    yearGroup,
                    yearGroupOther,
                    subjects,
                    subjectOther,
                    examBoards,
                },
                supportProfile: {
                    specialCategoryProvided: providesSpecialCategoryInformation,
                    needsStatus,
                    relevantAreas,
                    supportNeeds,
                    helpfulStrategies,
                    unhelpfulApproaches,
                    otherBackground,
                    ehcpStatus,
                },
                sessionPreferences: { sessionLength, sessionFrequency, widerSupport },
                confirmations: {
                    authorised: true,
                    privacyAcknowledged: true,
                    specialCategoryConsent: providesSpecialCategoryInformation,
                    specialCategoryAuthority: providesSpecialCategoryInformation,
                    learnerConsentRoute,
                },
            },
        },
    };
}

const CONSENT_WORDING_VERSION = 'secondary-child-explicit-consent-v1-2026-09-21';
const ADULT_CONSENT_WORDING_VERSION = 'adhd-adult-explicit-consent-v1-2026-09-21';
const AUTHORITY_WORDING_VERSION = 'secondary-special-category-authority-v1-2026-09-21';
const LEARNER_CONSENT_ROUTE_WORDING_VERSION = 'secondary-learner-consent-route-v1-2026-09-21';
const MAX_REQUEST_CHARACTERS = 50000;
const SIGNATURE_WINDOW_MILLISECONDS = 5 * 60 * 1000;
const DUPLICATE_CACHE_SECONDS = 6 * 60 * 60;
const SHEET_COLUMNS = [
  "Submission ID",
  "Worker accepted at (UTC)",
  "Google received at (UTC)",
  "Form version",
  "Respondent email",
  "Respondent first name",
  "Respondent surname",
  "Relationship to learner",
  "Relationship details",
  "Mobile number",
  "Preferred contact methods",
  "Suitable contact times",
  "Learner first name",
  "Learner surname",
  "Learner date of birth",
  "Year group or equivalent",
  "Year group details",
  "Subjects requiring support",
  "Other subject",
  "English exam board",
  "Maths exam board",
  "Science exam board",
  "Other subject exam board",
  "Needs status",
  "Relevant need areas",
  "Support needs information",
  "Helpful strategies",
  "Unhelpful approaches",
  "Other educational or personal background",
  "EHCP status",
  "Preferred session length",
  "Preferred session frequency",
  "Wider MentorSphere support discussion",
  "Authorised confirmation",
  "Privacy acknowledgement",
  "Special-category information provided",
  "Explicit consent",
  "Explicit consent wording version",
  "Consent recorded at (UTC)",
  "Parental responsibility or documented authority",
  "Authority wording version",
  "Learner consent route",
  "Learner consent route wording version",
  "Special-category consent status",
  "Consent withdrawn at (UTC)",
  "Notification status",
  "Notification sent at (UTC)",
  "Record status",
  "Last meaningful contact date",
  "Retention review date",
  "Safeguarding or legal hold",
  "Retention notes"
];

function jsonOutput_(value) {
  return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON);
}
function safeError_() {
  return jsonOutput_({ success: false, stored: false, status: 'rejected' });
}

function constantTimeEqual_(left, right) {
  if (typeof left !== 'string' || typeof right !== 'string') return false;
  let difference = left.length ^ right.length;
  const length = Math.max(left.length, right.length);
  for (let index = 0; index < length; index += 1) {
    difference |= (left.charCodeAt(index % Math.max(1, left.length)) || 0) ^
      (right.charCodeAt(index % Math.max(1, right.length)) || 0);
  }
  return difference === 0;
}

function expectedSignature_(body, secret) {
  const bytes = Utilities.computeHmacSha256Signature(body, secret, Utilities.Charset.UTF_8);
  return Utilities.base64EncodeWebSafe(bytes).replace(/=+$/u, '');
}

function isFreshTimestamp_(value) {
  const timestamp = new Date(value).getTime();
  if (!Number.isFinite(timestamp)) return false;
  const difference = Math.abs(Date.now() - timestamp);
  return difference <= SIGNATURE_WINDOW_MILLISECONDS;
}

function isObject_(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function hasValidShape_(request) {
  if (!isObject_(request) || !isFreshTimestamp_(request.issuedAt) || !isObject_(request.payload)) return false;
  return validateSecondaryRequest({ ...request.payload, turnstileToken: 'verified-signed-envelope', honeypot: '' }).ok;
}

function text_(value) {
  if (Array.isArray(value)) return value.map(text_).filter(Boolean).join(' | ');
  if (value === true) return 'Yes';
  if (value === false) return 'No';
  if (value === null || value === undefined) return '';
  const text = String(value).trim();
  return /^[=+\-@]/u.test(text) ? `'${text}` : text;
}

function canonicalContactMethods_(values) {
  return CONTACT_METHODS.filter((method) => values.indexOf(method) >= 0).join('; ');
}

function retentionReviewDate_(receivedAt) {
  const receivedDate = new Date(receivedAt);
  if (!Number.isFinite(receivedDate.getTime())) throw new Error('Invalid received date');
  const originalDay = receivedDate.getUTCDate();
  receivedDate.setUTCDate(1);
  receivedDate.setUTCMonth(receivedDate.getUTCMonth() + 6);
  const lastDayOfTargetMonth = new Date(Date.UTC(
    receivedDate.getUTCFullYear(),
    receivedDate.getUTCMonth() + 1,
    0,
  )).getUTCDate();
  receivedDate.setUTCDate(Math.min(originalDay, lastDayOfTargetMonth));
  return receivedDate.toISOString().slice(0, 10);
}

function rowFor_(request, receivedAt) {
  const payload = request.payload;
  return [
    payload.submissionId,
    request.issuedAt,
    receivedAt,
    payload.formVersion,
    payload.respondent.email,
    payload.respondent.firstName,
    payload.respondent.surname,
    payload.respondent.relationship,
    payload.respondent.relationshipOther,
    payload.respondent.mobile,
    canonicalContactMethods_(payload.respondent.preferredContactMethods),
    payload.respondent.suitableContactTimes,
    payload.learner.firstName,
    payload.learner.surname,
    payload.learner.dateOfBirth,
    payload.learner.yearGroup,
    payload.learner.yearGroupOther,
    payload.learner.subjects,
    payload.learner.subjectOther,
    payload.learner.examBoards.English,
    payload.learner.examBoards.Maths,
    payload.learner.examBoards.Science,
    payload.learner.examBoards.Other,
    payload.supportProfile.needsStatus,
    payload.supportProfile.relevantAreas,
    payload.supportProfile.supportNeeds,
    payload.supportProfile.helpfulStrategies,
    payload.supportProfile.unhelpfulApproaches,
    payload.supportProfile.otherBackground,
    payload.supportProfile.ehcpStatus,
    payload.sessionPreferences.sessionLength,
    payload.sessionPreferences.sessionFrequency,
    payload.sessionPreferences.widerSupport,
    payload.confirmations.authorised,
    payload.confirmations.privacyAcknowledged,
    payload.supportProfile.specialCategoryProvided,
    payload.confirmations.specialCategoryConsent,
    payload.supportProfile.specialCategoryProvided ? CONSENT_WORDING_VERSION : '',
    payload.supportProfile.specialCategoryProvided ? receivedAt : '',
    payload.confirmations.specialCategoryAuthority,
    payload.supportProfile.specialCategoryProvided ? AUTHORITY_WORDING_VERSION : '',
    payload.supportProfile.specialCategoryProvided ? payload.confirmations.learnerConsentRoute : '',
    payload.supportProfile.specialCategoryProvided ? LEARNER_CONSENT_ROUTE_WORDING_VERSION : '',
    payload.supportProfile.specialCategoryProvided ? 'Active' : 'Not applicable',
    '',
    'Pending',
    '',
    'Prospective',
    receivedAt.slice(0, 10),
    retentionReviewDate_(receivedAt),
    'No',
    ''
  ].map(text_);
}

function configuredSheet_(properties) {
  const spreadsheetId = properties.getProperty('SPREADSHEET_ID');
  const sheetName = properties.getProperty('SHEET_NAME');
  if (!spreadsheetId || !sheetName) throw new Error('Missing spreadsheet configuration');
  const sheet = SpreadsheetApp.openById(spreadsheetId).getSheetByName(sheetName);
  if (!sheet) throw new Error('Configured sheet was not found');
  return sheet;
}

function ensureHeaders_(sheet) {
  if (sheet.getLastRow() === 0) {
    const headerRange = sheet.getRange(1, 1, 1, SHEET_COLUMNS.length);
    headerRange.setNumberFormat('@');
    headerRange.setValues([SHEET_COLUMNS]);
    headerRange.setFontWeight('bold');
    sheet.setFrozenRows(1);
    return;
  }
  const headers = sheet.getRange(1, 1, 1, SHEET_COLUMNS.length).getDisplayValues()[0];
  if (headers.join('\u001f') !== SHEET_COLUMNS.join('\u001f')) throw new Error('Sheet headers do not match the integration schema');
}

function findSubmissionRow_(sheet, submissionId) {
  const lastRow = sheet.getLastRow();
  if (lastRow < 2) return 0;
  const match = sheet.getRange(2, 1, lastRow - 1, 1)
    .createTextFinder(submissionId)
    .matchEntireCell(true)
    .findNext();
  return match ? match.getRow() : 0;
}

function duplicateCacheKey_(submissionId) {
  return `stored:${submissionId}`;
}

function verifyStoredRow_(sheet, rowNumber, submissionId) {
  if (!Number.isInteger(rowNumber) || rowNumber < 2) return false;
  const storedRow = sheet.getRange(rowNumber, 1, 1, SHEET_COLUMNS.length).getValues()[0];
  return Array.isArray(storedRow) &&
    storedRow.length === SHEET_COLUMNS.length &&
    String(storedRow[0]) === submissionId &&
    String(storedRow[3]) === FORM_VERSION &&
    Number.isFinite(new Date(storedRow[2]).getTime()) &&
    String(storedRow[SHEET_COLUMNS.indexOf('Privacy acknowledgement')]) === 'Yes';
}

function verifyStoredPayload_(sheet, rowNumber, request) {
  const stored = sheet.getRange(rowNumber, 1, 1, SHEET_COLUMNS.length).getValues()[0];
  const canonical = rowFor_(request, String(stored[2]));
  const formColumnCount = SHEET_COLUMNS.indexOf('Notification status');
  return formColumnCount > 0 && canonical.slice(0, formColumnCount).every((value, index) =>
    index === 1 || String(stored[index]) === String(value));
}

function classifyDuplicate_(sheet, submissionId, cache, request) {
  const rowNumber = findSubmissionRow_(sheet, submissionId);
  if (rowNumber > 0) {
    return verifyStoredRow_(sheet, rowNumber, submissionId)
      ? (verifyStoredPayload_(sheet, rowNumber, request) ? { status: 'duplicate', rowNumber } : { status: 'duplicate_conflict', rowNumber: 0 })
      : { status: 'duplicate_without_record', rowNumber: 0 };
  }
  if (cache.get(duplicateCacheKey_(submissionId)) === 'stored') {
    return { status: 'duplicate_without_record', rowNumber: 0 };
  }
  return { status: 'new', rowNumber: 0 };
}

function appendSubmission_(sheet, row) {
  const targetRow = sheet.getLastRow() + 1;
  const range = sheet.getRange(targetRow, 1, 1, SHEET_COLUMNS.length);
  range.setNumberFormat('@');
  range.setValues([row]);
  return targetRow;
}

function testFlagEnabled_(properties, name) {
  return properties.getProperty('TEST_MODE') === 'true' && properties.getProperty(name) === 'true';
}

function sendMinimalNotification_(properties, receivedAt) {
  if (testFlagEnabled_(properties, 'FORCE_NOTIFICATION_FAILURE')) {
    throw new Error('Notification failure requested by isolated test configuration');
  }
  const recipient = properties.getProperty('NOTIFICATION_EMAIL');
  const privateSheetUrl = properties.getProperty('PRIVATE_SHEET_URL');
  if (!recipient || !privateSheetUrl) throw new Error('Missing notification configuration');
  MailApp.sendEmail({
    to: recipient,
    subject: 'New secondary learner profile received',
    body: [
      `A new intake form was received at ${receivedAt}.`,
      '',
      'Open the private response sheet:',
      privateSheetUrl,
      '',
      'This notification intentionally contains no learner or respondent answers.',
    ].join('\n'),
    name: 'The MentorSphere website',
  });
}

function doPost(event) {
  try {
    const raw = event && event.postData && typeof event.postData.contents === 'string'
      ? event.postData.contents
      : '';
    if (!raw || raw.length > MAX_REQUEST_CHARACTERS) return safeError_();

    const envelope = JSON.parse(raw);
    if (!isObject_(envelope) || typeof envelope.body !== 'string' || typeof envelope.signature !== 'string') return safeError_();

    const properties = PropertiesService.getScriptProperties();
    const secret = properties.getProperty('HMAC_SECRET');
    if (!secret || !constantTimeEqual_(envelope.signature, expectedSignature_(envelope.body, secret))) return safeError_();

    const request = JSON.parse(envelope.body);
    if (!hasValidShape_(request)) return safeError_();
    if (testFlagEnabled_(properties, 'FORCE_REQUEST_FAILURE')) return safeError_();

    const lock = LockService.getScriptLock();
    if (!lock.tryLock(10000)) return safeError_();

    const cache = CacheService.getScriptCache();
    let sheet;
    let rowNumber = 0;
    let duplicateStatus = 'new';
    const receivedAt = new Date().toISOString();
    try {
      sheet = configuredSheet_(properties);
      ensureHeaders_(sheet);
      const duplicateResult = classifyDuplicate_(sheet, request.payload.submissionId, cache, request);
      duplicateStatus = duplicateResult.status;
      rowNumber = duplicateResult.rowNumber;
      if (duplicateStatus === 'duplicate') {
        cache.put(duplicateCacheKey_(request.payload.submissionId), 'stored', DUPLICATE_CACHE_SECONDS);
      } else if (duplicateStatus === 'new') {
        const row = rowFor_(request, receivedAt);
        if (row.length !== SHEET_COLUMNS.length) throw new Error('Row mapping does not match schema');
        rowNumber = appendSubmission_(sheet, row);
        SpreadsheetApp.flush();
        if (!verifyStoredRow_(sheet, rowNumber, request.payload.submissionId) || !verifyStoredPayload_(sheet, rowNumber, request)) {
          throw new Error('Stored row could not be verified');
        }
        cache.put(duplicateCacheKey_(request.payload.submissionId), 'stored', DUPLICATE_CACHE_SECONDS);
      }
    } finally {
      lock.releaseLock();
    }

    if (duplicateStatus === 'duplicate') {
      return jsonOutput_({
        success: true,
        stored: false,
        status: 'duplicate',
        existingRecordVerified: true,
      });
    }
    if (duplicateStatus === 'duplicate_conflict') {
      return jsonOutput_({ success: false, stored: false, status: 'duplicate_conflict' });
    }
    if (duplicateStatus === 'duplicate_without_record') {
      return jsonOutput_({ success: false, stored: false, status: 'duplicate_without_record' });
    }

    const statusColumn = SHEET_COLUMNS.indexOf('Notification status') + 1;
    const sentAtColumn = SHEET_COLUMNS.indexOf('Notification sent at (UTC)') + 1;
    let notificationSent = false;
    if (properties.getProperty('TEST_MODE') === 'true' && !testFlagEnabled_(properties, 'FORCE_NOTIFICATION_FAILURE')) {
      sheet.getRange(rowNumber, statusColumn).setValue('Disabled: isolated test');
      SpreadsheetApp.flush();
      return jsonOutput_({ success: true, stored: true, status: 'created', notificationSent: false });
    }
    try {
      sendMinimalNotification_(properties, receivedAt);
      sheet.getRange(rowNumber, statusColumn).setValue('Sent');
      sheet.getRange(rowNumber, sentAtColumn).setValue(new Date().toISOString());
      SpreadsheetApp.flush();
      notificationSent = true;
    } catch (notificationError) {
      sheet.getRange(rowNumber, statusColumn).setValue('Failed: review Apps Script executions');
      SpreadsheetApp.flush();
    }

    return jsonOutput_({ success: true, stored: true, status: 'created', notificationSent });
  } catch (error) {
    return safeError_();
  }
}
