import type { KnowledgeEntry } from "./types";

const SITE = "https://www.thementorsphere.co.uk";

export const knowledgeBase: readonly KnowledgeEntry[] = [
  {
    id: "tutoring-scope",
    title: "Learning and tutoring subjects and levels",
    category: "tutoring",
    content:
      "The MentorSphere provides personalised one-to-one online tutoring in Maths, English and Science. Maths is offered from KS1 to KS4, including 11+, Functional Skills and selected post-16 topics by agreement. English is offered from KS1 to KS3, 11+ and GCSE English Language. The advertised GCSE English service is Language; support for a specific Literature course or text should be discussed before booking. Science is offered from KS1 to KS4, including GCSE Combined and separate sciences, with particular focus on Biology and Physics.",
    sourcePage: "Learning and tutoring",
    sourceUrl: `${SITE}/tutoring/`,
    documentVersion: "Current service page",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-30",
    keywords: ["maths", "english", "science", "ks1", "ks2", "ks3", "ks4", "gcse", "11+", "functional skills", "post-16"],
    alternativeTerms: ["lessons", "tuition", "tutor", "school work", "subject help", "special needs kids"],
    concepts: ["tutoring", "subjects", "levels", "learners", "send"],
    status: "current",
    priority: 7,
  },
  {
    id: "tutoring-delivery-lengths",
    title: "Tutoring delivery and session lengths",
    category: "tutoring",
    content:
      "Tutoring is delivered one-to-one online. Available session lengths are 30, 45, 60 and 90 minutes. The length can be chosen around age, attention, energy, topic and goals. A camera can help communication but is not automatically required throughout every session, and adjustments can be discussed.",
    sourcePage: "Learning and tutoring",
    sourceUrl: `${SITE}/tutoring/`,
    documentVersion: "Current service page",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-30",
    keywords: ["30 minutes", "45 minutes", "60 minutes", "90 minutes", "online", "camera", "lessonspace"],
    alternativeTerms: ["lesson length", "how long", "session duration", "zoom lesson", "remote lesson"],
    concepts: ["tutoring", "delivery", "session-length", "accessibility"],
    status: "current",
    priority: 6,
  },
  {
    id: "tutoring-onboarding",
    title: "Free introduction and learner profile",
    category: "tutoring",
    content:
      "Tutoring starts with a free, no-pressure introductory session. A starting-point assessment and personalised learner profile can bring together strengths, barriers, preferences and initial teaching strategies. Regular tutoring includes lesson planning, adapted resources, saved Lessonspace boards, brief progress communication and reasonable adaptations. Detailed reports or substantial additional work may be priced separately and agreed first.",
    sourcePage: "Learning and tutoring",
    sourceUrl: `${SITE}/tutoring/`,
    documentVersion: "Pricing Plan V3.1 and current service page",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-30",
    keywords: ["free", "introductory", "starting point", "learner profile", "planning", "saved boards", "progress"],
    alternativeTerms: ["trial lesson", "trial session", "discovery call", "intro call", "first meeting", "onboarding"],
    concepts: ["tutoring", "introduction", "onboarding", "included-support"],
    status: "current",
    priority: 7,
  },
  {
    id: "tutoring-payg-prices",
    title: "PAYG tutoring prices",
    category: "pricing",
    content:
      "Current PAYG prices for one-to-one Maths, English or Science tutoring are £22.50 for 30 minutes, £33.75 for 45 minutes, £45.00 for 60 minutes and £67.50 for 90 minutes.",
    sourcePage: "Pricing",
    sourceUrl: `${SITE}/pricing/#tutoring-prices`,
    documentVersion: "Pricing Plan V3.1",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-29",
    keywords: ["£22.50", "£33.75", "£45", "£67.50", "payg", "price", "cost", "tutoring"],
    alternativeTerms: ["pay as you go", "single lesson", "one-off lesson", "hourly rate"],
    concepts: ["tutoring", "pricing", "payg", "session-length"],
    status: "current",
    priority: 10,
  },
  {
    id: "tutoring-subscription-prices",
    title: "Monthly tutoring subscription plans",
    category: "pricing",
    content:
      "Representative four-week monthly prices are: Essentials, normally 2 sessions: £38 for 30 minutes, £58 for 45 minutes, £75 for 60 minutes or £109 for 90 minutes. Confidence Builder, normally 4 sessions: £77, £115, £150 or £218. Skills Booster, normally 8 sessions: £156, £226, £295 or £421. Fast-track, normally 12 sessions: £228, £335, £433 or £616. The values are listed in session-length order: 30, 45, 60 and 90 minutes.",
    sourcePage: "Pricing",
    sourceUrl: `${SITE}/pricing/#subscriptions`,
    documentVersion: "Pricing Plan V3.1",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-29",
    keywords: ["essentials", "confidence builder", "skills booster", "fast-track", "subscription", "monthly", "£38", "£150"],
    alternativeTerms: ["monthly tutoring package", "regular lesson plan", "fortnightly", "weekly", "twice weekly"],
    concepts: ["tutoring", "pricing", "subscription", "packages"],
    status: "current",
    priority: 10,
  },
  {
    id: "tutoring-subscription-calculation",
    title: "How calendar-month tutoring invoices are calculated",
    category: "pricing",
    content:
      "Subscription tables show representative prices for a standard four-week month. The actual invoice reflects the sessions scheduled in that calendar month. Additional or fewer sessions use the same plan-based discounted per-session rate, calculated by dividing the displayed plan price by its standard session count, with the final total rounded to the nearest penny. For example, four 60-minute Confidence Builder sessions cost £150, so five scheduled sessions cost £187.50.",
    sourcePage: "Pricing",
    sourceUrl: `${SITE}/pricing/#subscriptions`,
    documentVersion: "Pricing Plan V3.1",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-29",
    keywords: ["five week month", "calendar month", "invoice", "per-session rate", "£187.50", "school holidays"],
    alternativeTerms: ["variable month", "extra week", "monthly calculation", "why bill changed"],
    concepts: ["tutoring", "pricing", "subscription", "calculation"],
    status: "current",
    priority: 10,
  },
  {
    id: "tutoring-combined-family",
    title: "Combined subjects and family arrangements",
    category: "tutoring",
    content:
      "A tutoring plan can alternate subjects, split a longer session or change focus around current priorities, with the schedule and price agreed clearly. Family and multi-learner arrangements can also be discussed. The structure depends on whether sessions are shared or separate and on the planning involved.",
    sourcePage: "Pricing",
    sourceUrl: `${SITE}/pricing/#included`,
    documentVersion: "Pricing Plan V3.1",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-29",
    keywords: ["combine subjects", "siblings", "family", "multi-learner", "alternate", "shared session"],
    alternativeTerms: ["maths and english", "two children", "brother and sister", "split lesson"],
    concepts: ["tutoring", "combined-subjects", "family", "pricing"],
    status: "current",
    priority: 7,
  },
  {
    id: "coaching-audiences-boundaries",
    title: "ADHD coaching audiences and boundaries",
    category: "adhd-coaching",
    content:
      "Neurodiversity-affirming ADHD coaching is available for adults aged 18+, eligible young people aged 10 to 17, and parents or guardians supporting a young person with ADHD. Coaching is proactive, reflective and strategy-based. It is not therapy, psychotherapy, diagnosis, medical treatment or crisis support. A formal diagnosis is not automatically required to discuss suitability.",
    sourcePage: "ADHD coaching",
    sourceUrl: `${SITE}/adhd-coaching/`,
    documentVersion: "ADHD Coaching Policy V1.3",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-29",
    keywords: ["adhd", "18+", "10 to 17", "young people", "adult", "parent", "guardian", "not therapy", "not diagnosis"],
    alternativeTerms: ["adhd therapy", "executive function help", "teen coaching", "parent coaching", "child coaching"],
    concepts: ["adhd-coaching", "ages", "boundaries", "parents", "diagnosis"],
    status: "current",
    priority: 9,
  },
  {
    id: "coaching-content-delivery",
    title: "What ADHD coaching can cover",
    category: "adhd-coaching",
    content:
      "ADHD coaching can support routines, planning, organisation, everyday executive function, motivation, procrastination, task initiation, emotional regulation, school, work, study, relationships, identity, confidence and self-understanding. Standard sessions are normally 60 minutes and delivered online. Camera-off arrangements, breaks or shorter sessions can be discussed where appropriate.",
    sourcePage: "ADHD Coaching Policy",
    sourceUrl: `${SITE}/adhd-coaching-policy/`,
    documentVersion: "ADHD Coaching Policy V1.3",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-29",
    keywords: ["routines", "planning", "organisation", "motivation", "emotional regulation", "relationships", "60 minutes"],
    alternativeTerms: ["procrastination help", "productivity help", "executive dysfunction", "overwhelm", "task initiation"],
    concepts: ["adhd-coaching", "topics", "delivery", "accessibility"],
    status: "current",
    priority: 7,
  },
  {
    id: "coaching-family-involvement",
    title: "Parent or guardian involvement in young-person coaching",
    category: "adhd-coaching",
    content:
      "For a young person, the level of parent or guardian involvement is agreed according to age, needs, preferences and circumstances. Around one in every four sessions involving a parent or guardian is a general recommendation, not a fixed requirement. Involvement may be separate or part of a joint session. The young person's privacy and voice remain central, subject to safeguarding responsibilities.",
    sourcePage: "ADHD Coaching Policy",
    sourceUrl: `${SITE}/adhd-coaching-policy/`,
    documentVersion: "ADHD Coaching Policy V1.3",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-29",
    keywords: ["parent join", "guardian involvement", "one in four", "young person privacy", "joint session"],
    alternativeTerms: ["can mum join", "can dad attend", "family session", "parent sit in"],
    concepts: ["adhd-coaching", "young-people", "parents", "confidentiality"],
    status: "current",
    priority: 8,
  },
  {
    id: "coaching-self-funded-prices",
    title: "Self-funded ADHD coaching prices",
    category: "pricing",
    content:
      "A single self-funded 60-minute ADHD coaching session costs £70. A six-session package costs £390, which is £65 per session, and is valid for six months. A twelve-session package costs £740, approximately £61.67 per session, and is valid for twelve months. The same self-funded price applies to adults, eligible young people, and parents or guardians.",
    sourcePage: "Pricing",
    sourceUrl: `${SITE}/pricing/#adhd-coaching`,
    documentVersion: "Pricing Plan V3.1 and ADHD Coaching Policy V1.3",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-29",
    keywords: ["£70", "£390", "£740", "six sessions", "twelve sessions", "six months", "twelve months"],
    alternativeTerms: ["adhd coaching cost", "coaching package", "bundle", "single coaching session"],
    concepts: ["adhd-coaching", "pricing", "packages", "validity"],
    status: "current",
    priority: 10,
  },
  {
    id: "coaching-funded-prices",
    title: "Access to Work and employer-funded coaching",
    category: "pricing",
    content:
      "Access to Work-funded ADHD coaching and employer-funded individual ADHD coaching are each £110 per 60-minute session. Access to Work support is subject to written funding approval, and all funding decisions are made by Access to Work. The MentorSphere cannot promise eligibility or approval. School involvement, workplace consultations and ADHD workshops are scoped through a bespoke quotation. Self-funded package discounts do not automatically apply to funded or commissioned work.",
    sourcePage: "Pricing",
    sourceUrl: `${SITE}/pricing/#adhd-coaching`,
    documentVersion: "Pricing Plan V3.1 and ADHD Coaching Policy V1.3",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-29",
    keywords: ["access to work", "employer-funded", "£110", "school", "workplace", "workshops", "funding approval"],
    alternativeTerms: ["can work pay", "company funded", "employer pay", "atw", "government workplace funding"],
    concepts: ["adhd-coaching", "pricing", "employer-funded", "access-to-work", "funding"],
    status: "current",
    priority: 10,
  },
  {
    id: "coaching-existing-client-transition",
    title: "Existing ADHD coaching client price transition",
    category: "pricing",
    content:
      "Existing active coaching clients may continue at their previously agreed rates until 31 August 2026. Revised prices apply to new sessions and package renewals bought by existing clients from 1 September 2026. Packages purchased before that date remain valid at the agreed price for their stated validity period. Existing funded agreements continue at their agreed rate until the current approved period or agreement ends.",
    sourcePage: "ADHD Coaching Policy",
    sourceUrl: `${SITE}/adhd-coaching-policy/`,
    documentVersion: "ADHD Coaching Policy V1.3",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-29",
    validUntil: "2026-08-31",
    keywords: ["existing client", "transition", "31 august 2026", "1 september 2026", "old rate", "renewal"],
    alternativeTerms: ["current client price", "grandfathered rate", "price change"],
    concepts: ["adhd-coaching", "pricing", "transition"],
    status: "current",
    priority: 9,
  },
  {
    id: "education-send-scope",
    title: "Education and SEND support scope",
    category: "education-send",
    content:
      "Education and SEND support can help people understand education processes, organise information and prepare clear communications. Current pathways cover EHCP-related support, elective home education and EOTAS, private exams and access arrangements, and ADHD or autism referral preparation. It is practical preparation and guidance, not legal representation, clinical diagnosis, medical advice or statutory decision-making, and outcomes cannot be guaranteed.",
    sourcePage: "Education and SEND support",
    sourceUrl: `${SITE}/support-services/`,
    documentVersion: "Current service page",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-30",
    keywords: ["send", "sen", "ehcp", "ehe", "eotas", "private exams", "referral", "education support"],
    alternativeTerms: ["special educational needs", "special needs help", "sen help", "school system help", "education advice"],
    concepts: ["education-send", "scope", "boundaries", "support"],
    status: "current",
    priority: 9,
  },
  {
    id: "ehcp-support",
    title: "EHCP-related support",
    category: "education-send",
    content:
      "EHCP support may help a parent, family or young person understand where they are in the process, organise evidence, prepare clear requests, review information and plan questions for a meeting. The MentorSphere can support preparation and communication but does not provide legal representation, make local-authority decisions or guarantee an EHCP outcome.",
    sourcePage: "EHCP support",
    sourceUrl: `${SITE}/support-services/ehcp-support/`,
    documentVersion: "Current service page",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-30",
    keywords: ["ehcp", "evidence", "local authority", "meeting", "education health and care plan"],
    alternativeTerms: ["sort an ehcp", "get an ehcp", "education plan", "ehcp application", "ehcp review"],
    concepts: ["education-send", "ehcp", "documents", "boundaries"],
    status: "current",
    priority: 9,
  },
  {
    id: "ehe-eotas-support",
    title: "Elective home education and EOTAS support",
    category: "education-send",
    content:
      "The MentorSphere can provide practical education planning and preparation for elective home education, sometimes called home schooling, and for EOTAS contexts. This may include curriculum planning, realistic timetables, progress evidence and organising information. EHE and EOTAS are different routes; the free initial discussion helps clarify which context applies. The service is not legal representation or advice.",
    sourcePage: "Home education and EOTAS support",
    sourceUrl: `${SITE}/support-services/ehe-eotas/`,
    documentVersion: "Current service page",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-30",
    keywords: ["elective home education", "ehe", "eotas", "curriculum", "timetable", "progress evidence"],
    alternativeTerms: ["home schooling", "homeschooling", "education at home", "education outside school"],
    concepts: ["education-send", "ehe", "eotas", "home-education"],
    status: "current",
    priority: 9,
  },
  {
    id: "private-exams",
    title: "Private exams and access arrangements",
    category: "education-send",
    content:
      "Support may include guidance with private exam entry, finding or communicating with examination centres, organising supporting evidence and preparing for access-arrangement discussions. The MentorSphere does not make awarding or access-arrangement decisions and cannot guarantee an exam centre's decision.",
    sourcePage: "Private exams and access arrangements",
    sourceUrl: `${SITE}/support-services/private-exams/`,
    documentVersion: "Current service page",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-30",
    keywords: ["private exam", "private candidate", "exam centre", "access arrangement", "awarding organisation"],
    alternativeTerms: ["sit gcse privately", "exam booking", "extra time", "exam access help"],
    concepts: ["education-send", "private-exams", "access-arrangements", "boundaries"],
    status: "current",
    priority: 8,
  },
  {
    id: "referral-preparation",
    title: "ADHD and autism referral preparation",
    category: "education-send",
    content:
      "Referral preparation can help an adult, parent, family or young person organise examples, screening information and questions before speaking with a GP, education professional or assessment provider. It does not diagnose ADHD or autism, make a referral, provide medical advice or guarantee access to an assessment or a diagnostic outcome. Only an appropriately qualified clinical professional can diagnose.",
    sourcePage: "ADHD and autism referral preparation",
    sourceUrl: `${SITE}/support-services/referral-preparation/`,
    documentVersion: "Current service page",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-30",
    keywords: ["adhd referral", "autism referral", "assessment", "screening information", "gp", "diagnose"],
    alternativeTerms: ["help getting assessed", "diagnosis help", "can you diagnose", "assessment help", "referral support"],
    concepts: ["education-send", "referral-preparation", "diagnosis", "assessment", "boundaries"],
    status: "current",
    priority: 10,
  },
  {
    id: "education-send-pricing",
    title: "Education and SEND support pricing",
    category: "pricing",
    content:
      "Education and SEND support begins with a free initial discussion. Paid work is quoted according to the scope, deadline, preparation and expected output. A one-hour strategy conversation is different from reviewing several reports and preparing a detailed document. The proposed scope and fee are provided before substantive paid work begins. No single standard price is published for this bespoke work.",
    sourcePage: "Pricing",
    sourceUrl: `${SITE}/pricing/#support-pricing`,
    documentVersion: "Pricing Plan V3.1",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-29",
    keywords: ["bespoke quotation", "quoted", "scope", "free initial discussion", "support price", "document review"],
    alternativeTerms: ["how much is ehcp help", "send support cost", "home education price", "assessment help price"],
    concepts: ["education-send", "pricing", "bespoke"],
    status: "current",
    priority: 10,
  },
  {
    id: "cancellation-general-payg",
    title: "Cancellation and rescheduling for PAYG sessions",
    category: "booking",
    content:
      "The standard notice period for cancelling or rescheduling is 48 hours. With at least 48 hours' notice, a PAYG or prepaid session can normally be rearranged or cancelled without charge. With less notice, The MentorSphere will try to rearrange and will consider disability, neurodivergence, illness, family circumstances and unexpected events reasonably and flexibly. A replacement is not guaranteed. If one cannot reasonably be arranged, the session may remain chargeable or be treated as used. No separate standard late-cancellation fee is added on top.",
    sourcePage: "Pricing and booking terms",
    sourceUrl: `${SITE}/pricing/#terms`,
    documentVersion: "PAYG and Subscription Terms, current published wording",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-29",
    keywords: ["48 hours", "cancel", "reschedule", "miss", "late", "payg", "chargeable", "illness"],
    alternativeTerms: ["miss a lesson", "cannot attend", "move my session", "late cancellation", "sick"],
    concepts: ["booking", "cancellation", "rescheduling", "payg", "flexibility"],
    status: "current",
    priority: 10,
  },
  {
    id: "subscription-terms",
    title: "Subscription payment, replacement and cancellation terms",
    category: "booking",
    content:
      "Subscription payments reserve regular availability for the billing month and are not normally refundable once that month has begun, except where required by law or where The MentorSphere cannot provide the agreed service. A short-notice missed session will be rearranged where reasonably possible, normally within 60 days; otherwise it may be treated as used. A plan can be changed or cancelled with written notice. To prevent the next payment, notice must arrive at least 10 working days before the payment date; later notice may take effect from the following billing cycle.",
    sourcePage: "Pricing and booking terms",
    sourceUrl: `${SITE}/pricing/#terms`,
    documentVersion: "PAYG and Subscription Terms, current published wording",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-29",
    keywords: ["subscription", "10 working days", "60 days", "refund", "next payment", "billing month", "replacement"],
    alternativeTerms: ["cancel monthly plan", "stop direct debit", "miss subscription lesson", "banked session"],
    concepts: ["booking", "subscription", "cancellation", "payment", "replacement"],
    status: "current",
    priority: 10,
  },
  {
    id: "bespoke-cancellation-provider",
    title: "Bespoke-work and MentorSphere cancellation terms",
    category: "booking",
    content:
      "For bespoke work, any service-specific cancellation arrangement should be explained in writing before work begins. If a customer cancels after work has started, a proportionate amount may be retained or charged for completed work, committed time, non-recoverable third-party costs and direct losses, without double charging. If The MentorSphere cancels a session, the customer is offered a replacement, an account credit or a refund where a suitable replacement cannot be provided.",
    sourcePage: "Pricing and booking terms",
    sourceUrl: `${SITE}/pricing/#terms`,
    documentVersion: "PAYG and Subscription Terms, current published wording",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-29",
    keywords: ["bespoke cancellation", "work begun", "third-party costs", "mentor sphere cancels", "refund", "credit"],
    alternativeTerms: ["you cancel my lesson", "provider cancellation", "cancel document work"],
    concepts: ["booking", "bespoke", "cancellation", "refund"],
    status: "current",
    priority: 9,
  },
  {
    id: "technical-requirements",
    title: "Technical requirements and troubleshooting",
    category: "policy",
    content:
      "Online sessions normally need a laptop, desktop or tablet, working microphone and speakers or headphones, and a stable connection of at least 5 Mbps download, with 10 Mbps or more preferable. Use a current version of Chrome, Edge or Safari. Lessonspace normally runs in the browser without a download. Smartphones are not recommended for tutoring because the smaller screen limits whiteboard and resource use. A webcam is recommended but can be adapted. A touchscreen or stylus can help but is not essential.",
    sourcePage: "Technical Requirements and Troubleshooting Policy",
    sourceUrl: `${SITE}/technical-requirements/`,
    documentVersion: "V1.1",
    effectiveDate: "2025-05-12",
    lastReviewed: "2026-07-28",
    keywords: ["5 mbps", "10 mbps", "laptop", "tablet", "smartphone", "chrome", "edge", "safari", "lessonspace", "webcam"],
    alternativeTerms: ["computer requirements", "internet speed", "what device", "technical problem", "lesson link"],
    concepts: ["technical", "delivery", "accessibility", "troubleshooting"],
    status: "current",
    priority: 8,
  },
  {
    id: "cover-tutors",
    title: "Cover tutors and temporary staff",
    category: "policy",
    content:
      "A cover tutor may be considered for illness, leave, professional obligations or temporary staffing needs, but cover is not guaranteed. The MentorSphere should inform the learner or family in advance wherever possible. Cover tutors must meet appropriate experience, safeguarding, confidentiality and inclusive-practice standards, and receive only the learner information needed for safe delivery. A session may instead be rearranged, banked, credited or refunded under the relevant agreement.",
    sourcePage: "Cover Tutor and Temporary Staff Policy",
    sourceUrl: `${SITE}/cover-tutor-policy/`,
    documentVersion: "V1.0",
    effectiveDate: "2025-07-14",
    lastReviewed: "2026-07-28",
    keywords: ["cover tutor", "temporary staff", "another tutor", "dbs", "handover", "cover session"],
    alternativeTerms: ["someone else teaching", "replacement tutor", "substitute teacher", "different tutor"],
    concepts: ["cover-tutor", "staffing", "safeguarding", "privacy"],
    status: "current",
    priority: 9,
  },
  {
    id: "privacy",
    title: "Privacy and personal information",
    category: "policy",
    content:
      "The Privacy Policy explains how The MentorSphere collects, uses, protects and shares personal information for tutoring, coaching, support services and the website. Personal data is not sold or rented. Information is shared with trusted providers only where needed for delivery, payments or legal and safeguarding duties. Visitors should not use the initial contact form or this chatbot to send detailed medical records, identification documents or other highly sensitive information.",
    sourcePage: "Privacy Policy",
    sourceUrl: `${SITE}/privacy-policy/`,
    documentVersion: "V1.4",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-29",
    keywords: ["privacy", "personal data", "gdpr", "records", "third party", "confidential", "medical records"],
    alternativeTerms: ["what happens to my data", "data protection", "keep messages", "information sharing"],
    concepts: ["privacy", "data", "confidentiality"],
    status: "current",
    priority: 9,
  },
  {
    id: "safeguarding",
    title: "Safeguarding Policy",
    category: "policy",
    content:
      "Luke Turner is the Designated Safeguarding Lead. The Safeguarding Policy covers recognising, recording and responding to concerns, online session safety, confidentiality limits and reporting. The website, chatbot and business contact number are not monitored as emergency services. In immediate danger, call 999. Do not use the chatbot to submit a detailed safeguarding disclosure.",
    sourcePage: "Safeguarding Policy",
    sourceUrl: `${SITE}/safeguarding-policy/`,
    documentVersion: "V1.2",
    effectiveDate: "2025-09-08",
    lastReviewed: "2026-07-29",
    keywords: ["safeguarding", "designated safeguarding lead", "dsl", "luke turner", "concern", "999", "unsafe"],
    alternativeTerms: ["report a concern", "child safety", "disclosure", "abuse"],
    concepts: ["safeguarding", "emergency", "boundaries"],
    status: "current",
    priority: 10,
  },
  {
    id: "accessibility-send-policy",
    title: "Accessibility, reasonable adjustments and neurodiversity",
    category: "policy",
    content:
      "The MentorSphere aims to provide calm, accessible and neurodiversity-affirming support. Adjustments may include camera-off participation, breaks, shorter or differently structured sessions, reduced written administration, a verbal-first approach, processing time, flexible communication and changes to visual presentation. Requests are considered individually according to need, safety, service boundaries and available resources. A diagnosis is not generally required to discuss a barrier or adjustment.",
    sourcePage: "Accessibility Statement",
    sourceUrl: `${SITE}/accessibility/`,
    documentVersion: "Current statement and SEND, SEMH and Neurodiversity Policy V1.1",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-30",
    keywords: ["accessibility", "reasonable adjustments", "camera off", "breaks", "verbal first", "processing time", "diagnosis"],
    alternativeTerms: ["accommodation", "adapt session", "sensory needs", "communication needs", "special requirements"],
    concepts: ["accessibility", "adjustments", "send", "neurodiversity"],
    status: "current",
    priority: 9,
  },
  {
    id: "equality-inclusion",
    title: "Equality, Diversity and Inclusion Policy",
    category: "policy",
    content:
      "The current Equality, Diversity and Inclusion Policy is V2.0, effective 30 July 2026. It applies across tutoring, ADHD coaching, education and SEND support, commissioned work and staffing. It covers fair access, reasonable adjustments, neurodiversity-affirming practice, identity, unacceptable conduct and how to raise an equality concern. Equality-related complaints are handled under the Complaints Policy.",
    sourcePage: "Equality, Diversity and Inclusion Policy",
    sourceUrl: `${SITE}/equality-diversity-inclusion-policy/`,
    documentVersion: "V2.0",
    effectiveDate: "2026-07-30",
    lastReviewed: "2026-07-30",
    keywords: ["equality", "diversity", "inclusion", "discrimination", "protected characteristic", "pronouns", "reasonable adjustment"],
    alternativeTerms: ["edi", "equal opportunities", "unfair treatment", "access needs"],
    concepts: ["equality", "inclusion", "accessibility", "complaints"],
    status: "current",
    priority: 9,
  },
  {
    id: "complaints",
    title: "Complaints Policy",
    category: "policy",
    content:
      "The current Complaints Policy is V2.0, effective 30 July 2026. Concerns should normally be raised with Luke Turner as soon as reasonably possible so they can be understood and addressed. The policy explains the complaint stages, accessibility and support, response expectations, records, safeguarding priority and possible external routes. The policy page should be read for the exact current procedure.",
    sourcePage: "Complaints Policy",
    sourceUrl: `${SITE}/complaints-policy/`,
    documentVersion: "V2.0",
    effectiveDate: "2026-07-30",
    lastReviewed: "2026-07-30",
    keywords: ["complaint", "complaints policy", "concern", "feedback", "unhappy", "raise a complaint"],
    alternativeTerms: ["make a complaint", "formal complaint", "not happy", "problem with service"],
    concepts: ["complaints", "feedback", "policy"],
    status: "current",
    priority: 9,
  },
  {
    id: "contact",
    title: "Contacting The MentorSphere",
    category: "contact",
    content:
      "To ask about services or arrange a free introduction, use the website contact page. You can also email luke@thementorsphere.co.uk or telephone 07955 723 133. The MentorSphere supports clients predominantly online across the UK and is not an emergency service.",
    sourcePage: "Contact",
    sourceUrl: `${SITE}/contact/`,
    documentVersion: "Current contact page",
    effectiveDate: "2026-07-28",
    lastReviewed: "2026-07-30",
    keywords: ["contact", "email", "telephone", "07955 723 133", "luke@thementorsphere.co.uk", "book", "free introduction"],
    alternativeTerms: ["speak to luke", "get in touch", "enquire", "phone number", "email address", "book call"],
    concepts: ["contact", "booking", "introduction"],
    status: "current",
    priority: 9,
  },
  {
    id: "excluded-old-maths-mentor-policies",
    title: "Superseded Maths Mentor-only policies",
    category: "policy",
    content:
      "Older Equality and Diversity or Complaints policies branded only as The Maths Mentor are superseded and must not be used.",
    sourcePage: "Internal exclusion control",
    sourceUrl: `${SITE}/policies/`,
    documentVersion: "Superseded",
    effectiveDate: "",
    lastReviewed: "2026-07-30",
    keywords: ["old policy", "maths mentor complaints", "maths mentor equality"],
    alternativeTerms: [],
    concepts: ["excluded", "policy"],
    status: "excluded",
    priority: 0,
  },
];

export function currentKnowledgeEntries(today = new Date()): readonly KnowledgeEntry[] {
  const day = today.toISOString().slice(0, 10);
  return knowledgeBase.filter(
    (entry) =>
      entry.status === "current" &&
      (!entry.effectiveDate || entry.effectiveDate <= day) &&
      (!entry.validUntil || entry.validUntil >= day),
  );
}
