import { describe, expect, it } from "vitest";
import { validateSecondaryRequest, YEAR_GROUPS, EHCP_STATUSES, SESSION_LENGTHS, SESSION_FREQUENCIES } from "../src/intake/secondary-validation";
import { LEARNER_CONSENT_ROUTES } from "../src/intake/validation";
import { validSecondaryRequest, section } from "./secondary-fixtures";
function consent(input: Record<string, unknown>) { Object.assign(section(input, "confirmations"), { specialCategoryConsent: true, specialCategoryAuthority: true, learnerConsentRoute: LEARNER_CONSENT_ROUTES[0] }); section(input, "supportProfile").specialCategoryProvided = true; }
describe("Secondary schema", () => {
    it.each([["respondent", "relationshipOther"], ["learner", "yearGroupOther"], ["learner", "subjectOther"]])("rejects hidden Other text %s.%s", (group, key) => { const input = validSecondaryRequest(); section(input, group)[key] = "Unexpected hidden narrative"; expect(validateSecondaryRequest(input).ok).toBe(false); });
    it.each(YEAR_GROUPS)("accepts %s with optional exam boards", yearGroup => { const input = validSecondaryRequest(); Object.assign(section(input, "learner"), { yearGroup, yearGroupOther: yearGroup.startsWith("Other") ? "Alternative programme" : "" }); expect(validateSecondaryRequest(input).ok).toBe(true); });
    it.each(["Not known", "Not applicable", "AQA", "Edexcel"])("accepts GCSE exam board %s", board => { const input = validSecondaryRequest(); const learner = section(input, "learner"); learner.yearGroup = "Year 11"; (learner.examBoards as Record<string, string>).Maths = board; const result = validateSecondaryRequest(input); expect(result.ok).toBe(true); if (result.ok)
        expect(result.request.submission.learner.examBoards.Maths).toBe(board); });
    it("rejects exam boards for unselected subjects", () => { const input = validSecondaryRequest(); (section(input, "learner").examBoards as Record<string, string>).Science = "AQA"; expect(validateSecondaryRequest(input).ok).toBe(false); });
    it("requires the subject and other descriptions", () => { const input = validSecondaryRequest(); Object.assign(section(input, "learner"), { subjects: ["Other"], yearGroup: YEAR_GROUPS[5] }); expect(validateSecondaryRequest(input).ok).toBe(false); });
    it.each(["Medical or health professional", "Friend", "Employer", "Education or support professional", "Other family member"])("permits ordinary information but rejects sensitive data from %s", relationship => { const input = validSecondaryRequest(); section(input, "respondent").relationship = relationship; expect(validateSecondaryRequest(input).ok).toBe(true); consent(input); expect(validateSecondaryRequest(input).ok).toBe(false); });
    it.each(LEARNER_CONSENT_ROUTES)("accepts documented learner consent route", route => { const input = validSecondaryRequest(); consent(input); section(input, "confirmations").learnerConsentRoute = route; expect(validateSecondaryRequest(input).ok).toBe(true); });
    it.each(["specialCategoryConsent", "specialCategoryAuthority", "learnerConsentRoute"])("rejects sensitive data without %s", key => { const input = validSecondaryRequest(); consent(input); section(input, "supportProfile").supportNeeds = "Fictional support"; section(input, "confirmations")[key] = key === "learnerConsentRoute" ? "" : false; expect(validateSecondaryRequest(input).ok).toBe(false); });
    it.each(["supportNeeds", "helpfulStrategies", "unhelpfulApproaches", "otherBackground", "ehcpStatus"])("rejects crafted ungated %s", key => { const input = validSecondaryRequest(); section(input, "supportProfile")[key] = key === "ehcpStatus" ? "Yes" : "Fictional sensitive text"; expect(validateSecondaryRequest(input).ok).toBe(false); });
    it.each(EHCP_STATUSES)("accepts consented EHCP option %s", ehcpStatus => { const input = validSecondaryRequest(); consent(input); section(input, "supportProfile").ehcpStatus = ehcpStatus; expect(validateSecondaryRequest(input).ok).toBe(true); });
    it("accepts legacy multiple session preferences", () => { const input = validSecondaryRequest(); Object.assign(section(input, "sessionPreferences"), { sessionLength: [...SESSION_LENGTHS], sessionFrequency: [...SESSION_FREQUENCIES] }); expect(validateSecondaryRequest(input).ok).toBe(true); });
    it.each(["Telephone", "Text message", "WhatsApp"])("requires mobile for %s", method => { const input = validSecondaryRequest(); section(input, "respondent").preferredContactMethods = [method]; expect(validateSecondaryRequest(input).ok).toBe(false); section(input, "respondent").mobile = "07700 900123"; expect(validateSecondaryRequest(input).ok).toBe(true); });
});
