// Generated by integrations/google-apps-script/build-intakes.mjs. Do not edit by hand.
// Standalone project ONLY: never install in or configure with the Primary production backend.
const CONTACT_METHODS = ["Email", "Telephone", "Text message", "WhatsApp"];
const LEARNER_CONSENT_ROUTES = [
    "The learner understands how this information will be used and has authorised me to communicate this consent on their behalf.",
    "The learner is not currently able to understand and give informed consent to this use of their information, so I am giving consent as a person with parental responsibility or documented legal authority.",
];
const FORM_VERSION = "adhd-coaching-intake-v1";
const SUPPORT_FOR = ["adult", "child", "parent", "combined"];
const ADHD_STATUS = ["Diagnosed", "Self-identified / suspected", "Waiting for assessment", "Unsure", "Prefer not to say", "Other"];
const ADULT_DIFFICULTIES = ["Starting tasks", "Procrastination", "Time management", "Emotional regulation", "Organisation", "Burnout", "Focus", "Impulsivity", "Not sure", "Other"];
const ADULT_PRIORITIES = ["Understanding how my brain works", "Practical strategies", "Accountability", "Emotional support", "Workplace navigation", "Unsure", "Other"];
const EDUCATIONAL_STAGES = ["Reception", "Years 1 to 6 / Primary", "Years 7 to 9 / KS3", "Years 10 to 11 / GCSE", "Sixth Form / College", "Other"];
const NEURODIVERGENCE = ["ADHD", "Autism / autistic", "Dyslexia", "Dyspraxia", "Dyscalculia", "Auditory processing difficulties", "Anxiety", "Not sure", "Other"];
const CHILD_DIFFICULTIES = ["Focusing in class", "Homework", "Emotional regulation", "Social interaction", "Morning routines", "Sleep", "Organisation", "School attendance", "Not sure", "Other"];
const HOUSEHOLD = ["Two-parent household", "Single-parent household", "Co-parenting across two homes", "Multi-generational household", "Supporting more than one child", "Other"];
const DAILY_IMPACT = ["Manageable: looking for adjustments", "Moderate: frequent stress", "Severe: significant current difficulty", "Not sure", "Other"];
const PARENT_HELP = ["Support strategies", "Understanding ADHD", "Navigating school / SEND / EHCP processes", "Emotional support for myself", "Reducing conflict", "Not sure", "Other"];
function record(value) { return value !== null && typeof value === "object" && !Array.isArray(value) ? value : {}; }
function validateAdhdRequest(input) {
    const errors = {};
    const data = record(input);
    const respondent = record(data.respondent), adult = record(data.adult), child = record(data.child), parent = record(data.parent), confirmations = record(data.confirmations);
    function text(source, key, path, max = 160, required = false) {
        const raw = source[key];
        if (typeof raw !== "string" || raw.trim().length > max || (required && !raw.trim())) {
            errors[path] = required ? "Enter this information." : `Use ${max} characters or fewer.`;
            return "";
        }
        return raw.trim();
    }
    function choice(source, key, path, allowed, required = false) {
        const value = text(source, key, path, 500, required);
        if (value && !allowed.includes(value))
            errors[path] = "Choose an available option.";
        return value;
    }
    function choices(source, key, path, allowed, required = false) {
        const value = source[key];
        if (!Array.isArray(value) || value.some(item => typeof item !== "string" || !allowed.includes(item)) || new Set(value).size !== value.length || (required && !value.length)) {
            errors[path] = "Choose from the available options.";
            return [];
        }
        return allowed.filter(item => value.includes(item));
    }
    function bool(key) {
        if (typeof confirmations[key] !== "boolean")
            errors[`confirmations.${key}`] = "Confirm this choice.";
        return confirmations[key] === true;
    }
    function other(source, key, path, selected) {
        const result = text(source, key, path, 1000);
        if (result && !(Array.isArray(selected) ? selected.includes("Other") : selected === "Other"))
            errors[path] = "Remove details for an option that is not selected.";
        return result;
    }
    if (data.formVersion !== FORM_VERSION)
        errors.formVersion = "Refresh the page before submitting.";
    const submissionId = text(data, "submissionId", "submissionId", 64, true);
    if (!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(submissionId))
        errors.submissionId = "Refresh the page before submitting.";
    const turnstileToken = text(data, "turnstileToken", "turnstileToken", 2048, true);
    const honeypot = text(data, "honeypot", "honeypot", 200);
    const firstName = text(respondent, "firstName", "respondent.firstName", 100, true), surname = text(respondent, "surname", "respondent.surname", 100, true);
    const email = text(respondent, "email", "respondent.email", 254, true);
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/u.test(email))
        errors["respondent.email"] = "Enter a valid email address.";
    const mobile = text(respondent, "mobile", "respondent.mobile", 40);
    const preferredContactMethods = choices(respondent, "preferredContactMethods", "respondent.preferredContactMethods", CONTACT_METHODS, true);
    if (preferredContactMethods.some(value => value !== "Email") && !mobile)
        errors["respondent.mobile"] = "Enter a contact number for the selected contact methods.";
    const supportFor = choice(data, "supportFor", "supportFor", SUPPORT_FOR, true);
    const hasAdult = supportFor === "adult", hasChild = supportFor === "child" || supportFor === "combined", hasParent = supportFor === "parent" || supportFor === "combined";
    const adultSpecialCategoryConsent = bool("adultSpecialCategoryConsent"), childSpecialCategoryConsent = bool("childSpecialCategoryConsent"), childSpecialCategoryAuthority = bool("childSpecialCategoryAuthority");
    const learnerConsentRoute = choice(confirmations, "learnerConsentRoute", "confirmations.learnerConsentRoute", LEARNER_CONSENT_ROUTES);
    if (confirmations.authorised !== true)
        errors["confirmations.authorised"] = "Confirm your authority to provide this information.";
    if (confirmations.privacyAcknowledged !== true)
        errors["confirmations.privacyAcknowledged"] = "Acknowledge the Privacy Policy.";
    if (adultSpecialCategoryConsent && !hasAdult && !hasParent)
        errors["confirmations.adultSpecialCategoryConsent"] = "Remove consent for a route that is not selected.";
    if (childSpecialCategoryConsent && (!hasChild || !childSpecialCategoryAuthority || !learnerConsentRoute))
        errors["confirmations.childSpecialCategoryConsent"] = "Complete child consent, parental or legal authority and the learner consent route.";
    if (!childSpecialCategoryConsent && (childSpecialCategoryAuthority || learnerConsentRoute))
        errors["confirmations.childSpecialCategoryAuthority"] = "Remove child authority and learner consent when optional child information is not provided.";
    const adhdStatus = choice(adult, "adhdStatus", "adult.adhdStatus", ADHD_STATUS);
    const adultDifficulties = choices(adult, "difficulties", "adult.difficulties", ADULT_DIFFICULTIES);
    const priority = choice(adult, "priority", "adult.priority", ADULT_PRIORITIES);
    const adultValues = { adhdStatus, adhdStatusOther: other(adult, "adhdStatusOther", "adult.adhdStatusOther", adhdStatus), difficulties: adultDifficulties, difficultiesOther: other(adult, "difficultiesOther", "adult.difficultiesOther", adultDifficulties), priority, priorityOther: other(adult, "priorityOther", "adult.priorityOther", priority) };
    const name = text(child, "name", "child.name", 200, hasChild);
    const age = text(child, "age", "child.age", 3, hasChild);
    if (hasChild && (!/^(0|[1-9]\d{0,2})$/.test(age) || Number(age) < 10 || Number(age) > 17))
        errors["child.age"] = "Direct young-person coaching is for ages 10 to 17. Use Parent/carer support for under 10s or Adult coaching for age 18 or over.";
    const educationalStage = choice(child, "educationalStage", "child.educationalStage", EDUCATIONAL_STAGES, hasChild);
    const educationalStageOther = other(child, "educationalStageOther", "child.educationalStageOther", educationalStage);
    const neurodivergence = choices(child, "neurodivergence", "child.neurodivergence", NEURODIVERGENCE), childDifficulties = choices(child, "difficulties", "child.difficulties", CHILD_DIFFICULTIES);
    const childSensitiveValues = { neurodivergence, neurodivergenceOther: other(child, "neurodivergenceOther", "child.neurodivergenceOther", neurodivergence), difficulties: childDifficulties, difficultiesOther: other(child, "difficultiesOther", "child.difficultiesOther", childDifficulties) };
    const household = choices(parent, "household", "parent.household", HOUSEHOLD), dailyImpact = choice(parent, "dailyImpact", "parent.dailyImpact", DAILY_IMPACT), help = choices(parent, "help", "parent.help", PARENT_HELP);
    const parentValues = { household, householdOther: other(parent, "householdOther", "parent.householdOther", household), dailyImpact, dailyImpactOther: other(parent, "dailyImpactOther", "parent.dailyImpactOther", dailyImpact), help, helpOther: other(parent, "helpOther", "parent.helpOther", help) };
    function hasValues(values) { return Object.values(values).some(value => Array.isArray(value) ? value.length > 0 : Boolean(value)); }
    if ((!hasAdult || !adultSpecialCategoryConsent) && hasValues(adultValues))
        errors.adult = "Remove adult information or give the appropriate explicit consent.";
    if ((!hasParent || !adultSpecialCategoryConsent) && hasValues(parentValues))
        errors.parent = "Remove parent information or give the appropriate explicit consent.";
    if ((!hasChild || !childSpecialCategoryConsent || !childSpecialCategoryAuthority || !learnerConsentRoute) && hasValues(childSensitiveValues))
        errors.child = "Remove optional child information or complete the child consent and authority route.";
    if (!hasChild && (name || age || educationalStage || educationalStageOther))
        errors.child = "Remove child details for a route that is not selected.";
    const additionalInformation = text(data, "additionalInformation", "additionalInformation", 5000);
    const additionalAllowed = (!hasAdult && !hasParent || adultSpecialCategoryConsent) && (!hasChild || childSpecialCategoryConsent && childSpecialCategoryAuthority && Boolean(learnerConsentRoute));
    if (additionalInformation && !additionalAllowed)
        errors.additionalInformation = "Complete the relevant consent routes before sharing optional additional information.";
    if (Object.keys(errors).length)
        return { ok: false, errors };
    return { ok: true, request: { turnstileToken, honeypot, submission: {
                formVersion: FORM_VERSION, submissionId, respondent: { firstName, surname, email, mobile, preferredContactMethods }, supportFor,
                adult: adultValues, child: { name, age, educationalStage, educationalStageOther, ...childSensitiveValues }, parent: parentValues,
                additionalInformation, confirmations: { authorised: true, privacyAcknowledged: true, adultSpecialCategoryConsent, childSpecialCategoryConsent, childSpecialCategoryAuthority, learnerConsentRoute },
            } } };
}

const CONSENT_WORDING_VERSION = 'adhd-child-explicit-consent-v1-2026-09-21';
const ADULT_CONSENT_WORDING_VERSION = 'adhd-adult-explicit-consent-v1-2026-09-21';
const AUTHORITY_WORDING_VERSION = 'adhd-special-category-authority-v1-2026-09-21';
const LEARNER_CONSENT_ROUTE_WORDING_VERSION = 'adhd-learner-consent-route-v1-2026-09-21';
const MAX_REQUEST_CHARACTERS = 50000;
const SIGNATURE_WINDOW_MILLISECONDS = 5 * 60 * 1000;
const DUPLICATE_CACHE_SECONDS = 6 * 60 * 60;
const SHEET_COLUMNS = [
  "Submission ID",
  "Worker accepted at (UTC)",
  "Google received at (UTC)",
  "Form version",
  "Respondent first name",
  "Respondent surname",
  "Respondent email",
  "Contact number",
  "Preferred contact methods",
  "Support for",
  "ADHD status",
  "ADHD status details",
  "Adult current difficulties",
  "Adult difficulty details",
  "Coaching priority",
  "Coaching priority details",
  "Child name",
  "Child age in completed years",
  "Educational stage",
  "Educational stage details",
  "Known or suspected neurodivergence",
  "Neurodivergence details",
  "Child current difficulties",
  "Child difficulty details",
  "Household context",
  "Household context details",
  "Daily impact",
  "Daily impact details",
  "Parent support preferences",
  "Parent support details",
  "Additional relevant information",
  "Ordinary information authority",
  "Privacy acknowledgement",
  "Adult explicit consent",
  "Adult consent wording version",
  "Adult consent recorded at (UTC)",
  "Adult consent status",
  "Adult consent withdrawn at (UTC)",
  "Child explicit consent",
  "Child consent wording version",
  "Child consent recorded at (UTC)",
  "Parental responsibility or documented authority",
  "Authority wording version",
  "Learner consent route",
  "Learner consent route wording version",
  "Child consent status",
  "Child consent withdrawn at (UTC)",
  "Notification status",
  "Notification sent at (UTC)",
  "Record status",
  "Last meaningful contact date",
  "Retention review date",
  "Safeguarding or legal hold",
  "Retention notes"
];

function jsonOutput_(value) {
  return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON);
}
function safeError_() {
  return jsonOutput_({ success: false, stored: false, status: 'rejected' });
}

function constantTimeEqual_(left, right) {
  if (typeof left !== 'string' || typeof right !== 'string') return false;
  let difference = left.length ^ right.length;
  const length = Math.max(left.length, right.length);
  for (let index = 0; index < length; index += 1) {
    difference |= (left.charCodeAt(index % Math.max(1, left.length)) || 0) ^
      (right.charCodeAt(index % Math.max(1, right.length)) || 0);
  }
  return difference === 0;
}

function expectedSignature_(body, secret) {
  const bytes = Utilities.computeHmacSha256Signature(body, secret, Utilities.Charset.UTF_8);
  return Utilities.base64EncodeWebSafe(bytes).replace(/=+$/u, '');
}

function isFreshTimestamp_(value) {
  const timestamp = new Date(value).getTime();
  if (!Number.isFinite(timestamp)) return false;
  const difference = Math.abs(Date.now() - timestamp);
  return difference <= SIGNATURE_WINDOW_MILLISECONDS;
}

function isObject_(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function hasValidShape_(request) {
  if (!isObject_(request) || !isFreshTimestamp_(request.issuedAt) || !isObject_(request.payload)) return false;
  return validateAdhdRequest({ ...request.payload, turnstileToken: 'verified-signed-envelope', honeypot: '' }).ok;
}

function text_(value) {
  if (Array.isArray(value)) return value.map(text_).filter(Boolean).join(' | ');
  if (value === true) return 'Yes';
  if (value === false) return 'No';
  if (value === null || value === undefined) return '';
  const text = String(value).trim();
  return /^['=+\-@]/u.test(text) ? `'${text}` : text;
}

function canonicalContactMethods_(values) {
  return CONTACT_METHODS.filter((method) => values.indexOf(method) >= 0).join('; ');
}

function retentionReviewDate_(receivedAt) {
  const receivedDate = new Date(receivedAt);
  if (!Number.isFinite(receivedDate.getTime())) throw new Error('Invalid received date');
  const originalDay = receivedDate.getUTCDate();
  receivedDate.setUTCDate(1);
  receivedDate.setUTCMonth(receivedDate.getUTCMonth() + 6);
  const lastDayOfTargetMonth = new Date(Date.UTC(
    receivedDate.getUTCFullYear(),
    receivedDate.getUTCMonth() + 1,
    0,
  )).getUTCDate();
  receivedDate.setUTCDate(Math.min(originalDay, lastDayOfTargetMonth));
  return receivedDate.toISOString().slice(0, 10);
}

function rowFor_(request, receivedAt) {
  const payload = request.payload;
  return [
    payload.submissionId,
    request.issuedAt,
    receivedAt,
    payload.formVersion,
    payload.respondent.firstName,
    payload.respondent.surname,
    payload.respondent.email,
    payload.respondent.mobile,
    canonicalContactMethods_(payload.respondent.preferredContactMethods),
    payload.supportFor,
    payload.adult.adhdStatus,
    payload.adult.adhdStatusOther,
    payload.adult.difficulties,
    payload.adult.difficultiesOther,
    payload.adult.priority,
    payload.adult.priorityOther,
    payload.child.name,
    payload.child.age,
    payload.child.educationalStage,
    payload.child.educationalStageOther,
    payload.child.neurodivergence,
    payload.child.neurodivergenceOther,
    payload.child.difficulties,
    payload.child.difficultiesOther,
    payload.parent.household,
    payload.parent.householdOther,
    payload.parent.dailyImpact,
    payload.parent.dailyImpactOther,
    payload.parent.help,
    payload.parent.helpOther,
    payload.additionalInformation,
    payload.confirmations.authorised,
    payload.confirmations.privacyAcknowledged,
    payload.confirmations.adultSpecialCategoryConsent,
    payload.confirmations.adultSpecialCategoryConsent ? ADULT_CONSENT_WORDING_VERSION : '',
    payload.confirmations.adultSpecialCategoryConsent ? receivedAt : '',
    payload.confirmations.adultSpecialCategoryConsent ? 'Active' : 'Not applicable',
    '',
    payload.confirmations.childSpecialCategoryConsent,
    payload.confirmations.childSpecialCategoryConsent ? CONSENT_WORDING_VERSION : '',
    payload.confirmations.childSpecialCategoryConsent ? receivedAt : '',
    payload.confirmations.childSpecialCategoryAuthority,
    payload.confirmations.childSpecialCategoryConsent ? AUTHORITY_WORDING_VERSION : '',
    payload.confirmations.learnerConsentRoute,
    payload.confirmations.childSpecialCategoryConsent ? LEARNER_CONSENT_ROUTE_WORDING_VERSION : '',
    payload.confirmations.childSpecialCategoryConsent ? 'Active' : 'Not applicable',
    '',
    'Pending',
    '',
    'Prospective',
    receivedAt.slice(0, 10),
    retentionReviewDate_(receivedAt),
    'No',
    ''
  ].map(text_);
}

function configuredSheet_(properties) {
  const spreadsheetId = properties.getProperty('SPREADSHEET_ID');
  const sheetName = properties.getProperty('SHEET_NAME');
  if (!spreadsheetId || !sheetName) throw new Error('Missing spreadsheet configuration');
  const sheet = SpreadsheetApp.openById(spreadsheetId).getSheetByName(sheetName);
  if (!sheet) throw new Error('Configured sheet was not found');
  return sheet;
}

function ensureHeaders_(sheet) {
  if (sheet.getLastRow() === 0) {
    const headerRange = sheet.getRange(1, 1, 1, SHEET_COLUMNS.length);
    headerRange.setNumberFormat('@');
    headerRange.setValues([SHEET_COLUMNS]);
    headerRange.setFontWeight('bold');
    sheet.setFrozenRows(1);
    return;
  }
  const headers = sheet.getRange(1, 1, 1, SHEET_COLUMNS.length).getDisplayValues()[0];
  if (headers.join('\u001f') !== SHEET_COLUMNS.join('\u001f')) throw new Error('Sheet headers do not match the integration schema');
}

function findSubmissionRow_(sheet, submissionId) {
  const lastRow = sheet.getLastRow();
  if (lastRow < 2) return 0;
  const match = sheet.getRange(2, 1, lastRow - 1, 1)
    .createTextFinder(submissionId)
    .matchEntireCell(true)
    .findNext();
  return match ? match.getRow() : 0;
}

function duplicateCacheKey_(submissionId) {
  return `stored:${submissionId}`;
}

function verifyStoredRow_(sheet, rowNumber, submissionId) {
  if (!Number.isInteger(rowNumber) || rowNumber < 2) return false;
  const storedRow = sheet.getRange(rowNumber, 1, 1, SHEET_COLUMNS.length).getValues()[0];
  return Array.isArray(storedRow) &&
    storedRow.length === SHEET_COLUMNS.length &&
    String(storedRow[0]) === submissionId &&
    String(storedRow[3]) === FORM_VERSION &&
    Number.isFinite(new Date(storedRow[2]).getTime()) &&
    String(storedRow[SHEET_COLUMNS.indexOf('Privacy acknowledgement')]) === 'Yes';
}

function verifyStoredPayload_(sheet, rowNumber, request) {
  const range = sheet.getRange(rowNumber, 1, 1, SHEET_COLUMNS.length);
  const stored = range.getValues()[0];
  const formulas = range.getFormulas()[0];
  const canonical = rowFor_(request, String(stored[2]));
  const formColumnCount = SHEET_COLUMNS.indexOf('Notification status');
  // Compare readback to readback: Sheets consumes one leading text-escape apostrophe.
  // Never normalise stored answers or accept a formula with a coincidentally equal value.
  return formColumnCount > 0 && canonical.slice(0, formColumnCount).every((value, index) =>
    formulas[index] === '' && (index === 1 || stored[index] === (value.startsWith("'") ? value.slice(1) : value)));
}

function classifyDuplicate_(sheet, submissionId, cache, request) {
  const rowNumber = findSubmissionRow_(sheet, submissionId);
  if (rowNumber > 0) {
    return verifyStoredRow_(sheet, rowNumber, submissionId)
      ? (verifyStoredPayload_(sheet, rowNumber, request) ? { status: 'duplicate', rowNumber } : { status: 'duplicate_conflict', rowNumber: 0 })
      : { status: 'duplicate_without_record', rowNumber: 0 };
  }
  if (!cache) throw new Error('Duplicate cache unavailable before storage');
  if (cache.get(duplicateCacheKey_(submissionId)) === 'stored') {
    return { status: 'duplicate_without_record', rowNumber: 0 };
  }
  return { status: 'new', rowNumber: 0 };
}

function appendSubmission_(sheet, row) {
  const targetRow = sheet.getLastRow() + 1;
  const range = sheet.getRange(targetRow, 1, 1, SHEET_COLUMNS.length);
  range.setNumberFormat('@');
  range.setValues([row]);
  return targetRow;
}

function testFlagEnabled_(properties, name) {
  return properties.getProperty('TEST_MODE') === 'true' && properties.getProperty(name) === 'true';
}

function sendMinimalNotification_(properties, receivedAt) {
  if (testFlagEnabled_(properties, 'FORCE_NOTIFICATION_FAILURE')) {
    throw new Error('Notification failure requested by isolated test configuration');
  }
  const recipient = properties.getProperty('NOTIFICATION_EMAIL');
  const privateSheetUrl = properties.getProperty('PRIVATE_SHEET_URL');
  if (!recipient || !privateSheetUrl) throw new Error('Missing notification configuration');
  MailApp.sendEmail({
    to: recipient,
    subject: 'New coaching intake received',
    body: [
      `A new intake form was received at ${receivedAt}.`,
      '',
      'Open the private response sheet:',
      privateSheetUrl,
      '',
      'This notification intentionally contains no learner or respondent answers.',
    ].join('\n'),
    name: 'The MentorSphere website',
  });
}

// Shared by the generated Secondary and ADHD receivers only. Never installed in Primary.
function rememberVerifiedSubmission_(cache, submissionId) {
  try {
    if (cache) cache.put(duplicateCacheKey_(submissionId), 'stored', DUPLICATE_CACHE_SECONDS);
  } catch (cacheError) {
    // The verified Sheet row is authoritative; a cache write is only an optimisation.
  }
}

function updateNotificationStatus_(sheet, rowNumber, status, sentAt) {
  try {
    sheet.getRange(rowNumber, SHEET_COLUMNS.indexOf('Notification sent at (UTC)') + 1).setValue(sentAt);
    sheet.getRange(rowNumber, SHEET_COLUMNS.indexOf('Notification status') + 1).setValue(status);
    SpreadsheetApp.flush();
  } catch (statusError) {
    // Administrative cells are best effort after the exact submission is committed.
    // Do not log exceptions: service errors can contain submitted data.
  }
}

function doPost(event) {
  let accepted = null;
  try {
    const raw = event && event.postData && typeof event.postData.contents === 'string'
      ? event.postData.contents
      : '';
    if (!raw || raw.length > MAX_REQUEST_CHARACTERS) return safeError_();

    const envelope = JSON.parse(raw);
    if (!isObject_(envelope) || typeof envelope.body !== 'string' || typeof envelope.signature !== 'string') return safeError_();

    const properties = PropertiesService.getScriptProperties();
    const secret = properties.getProperty('HMAC_SECRET');
    if (!secret || !constantTimeEqual_(envelope.signature, expectedSignature_(envelope.body, secret))) return safeError_();

    const request = JSON.parse(envelope.body);
    if (!hasValidShape_(request)) return safeError_();
    if (testFlagEnabled_(properties, 'FORCE_REQUEST_FAILURE')) return safeError_();

    const lock = LockService.getScriptLock();
    if (!lock.tryLock(10000)) return safeError_();

    let sheet;
    let rowNumber = 0;
    let duplicateStatus = 'new';
    const receivedAt = new Date().toISOString();
    try {
      let cache = null;
      try { cache = CacheService.getScriptCache(); } catch (cacheError) { /* Sheet lookup still runs. */ }
      sheet = configuredSheet_(properties);
      ensureHeaders_(sheet);
      const duplicateResult = classifyDuplicate_(sheet, request.payload.submissionId, cache, request);
      duplicateStatus = duplicateResult.status;
      rowNumber = duplicateResult.rowNumber;
      if (duplicateStatus === 'duplicate') {
        accepted = { success: true, stored: false, status: 'duplicate', existingRecordVerified: true };
      } else if (duplicateStatus === 'new') {
        const row = rowFor_(request, receivedAt);
        if (row.length !== SHEET_COLUMNS.length) throw new Error('Row mapping does not match schema');
        rowNumber = appendSubmission_(sheet, row);
        SpreadsheetApp.flush();
        if (!verifyStoredRow_(sheet, rowNumber, request.payload.submissionId) || !verifyStoredPayload_(sheet, rowNumber, request)) {
          throw new Error('Stored row could not be verified');
        }
        // Commit point: no subsequent cache, lock, mail or status error may erase this result.
        accepted = { success: true, stored: true, status: 'created', notificationSent: false };
      }
      if (accepted) rememberVerifiedSubmission_(cache, request.payload.submissionId);
    } finally {
      try { lock.releaseLock(); } catch (lockError) {
        if (!accepted) throw lockError;
      }
    }

    if (duplicateStatus === 'duplicate') return jsonOutput_(accepted);
    if (duplicateStatus === 'duplicate_conflict') {
      return jsonOutput_({ success: false, stored: false, status: 'duplicate_conflict' });
    }
    if (duplicateStatus === 'duplicate_without_record') {
      return jsonOutput_({ success: false, stored: false, status: 'duplicate_without_record' });
    }

    // Isolated test mode suppresses real mail unless testing its forced failure path.
    if (properties.getProperty('TEST_MODE') === 'true' && !testFlagEnabled_(properties, 'FORCE_NOTIFICATION_FAILURE')) {
      updateNotificationStatus_(sheet, rowNumber, 'Disabled: isolated test', '');
      return jsonOutput_(accepted);
    }
    try {
      sendMinimalNotification_(properties, receivedAt);
      accepted.notificationSent = true;
    } catch (notificationError) {
      // A notification failure does not change the confirmed storage result.
    }
    updateNotificationStatus_(sheet, rowNumber,
      accepted.notificationSent ? 'Sent' : 'Failed: review Apps Script executions',
      accepted.notificationSent ? new Date().toISOString() : '');
    return jsonOutput_(accepted);
  } catch (error) {
    // Pre-commit failures remain closed; post-commit failures preserve the receipt.
    return accepted ? jsonOutput_(accepted) : safeError_();
  }
}
